// <auto-generated />
using Gyarkorlas1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gyarkorlas1.Migrations
{
    [DbContext(typeof(KonyvtarDBContext))]
    [Migration("20260914080656_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Gyarkorlas1.Models.Konyv", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ar")
                        .HasColumnType("REAL");

                    b.Property<string>("cim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("kiadas_eve")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("szerzo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("konyvek");
                });
#pragma warning restore 612, 618
        }
    }
}
